Feature/24941 make installable
magenta-aps/mox_cpr_delta_mo pull request #2
Opened 2018-11-16 08:20 UTC by jgj-magenta-aps

This should make module able to be installed as a program using our salt stack.

2018-11-16 13:13 UTC, istherepie requested changes
The settings.py file is currently placed outside the scope of the package while it is specified that the file must exist in the path, is there any reason the file has not been included in the package ?

Additionally a flake8 check reveals cosmetic issues with the unit tests (line length and whitespaces).

2018-11-19 09:01 UTC, jgj-magenta-aps commented
I will look into it today. 
I had envisioned the package as installed like an application, given that it has it's own cache - since it is before 'integrationdata', but there is actually no reason for that - it can be transformed into a package, except for the requirements.txt, which has to stay outside.

2018-12-13 12:19 UTC, istherepie requested changes
I am unable to run the unit tests as these depend on a configuration file - it may be beneficial to include either defaults/fallback values or a dummy configuration file in order to run the tests.

2018-12-13 12:19 UTC, istherepie commented on mox_cpr_delta_mo/__main__.py
> +from .settings import (
It is preferable to use explicit import.

2018-12-20 13:51 UTC, istherepie approved these changes

2018-12-20 14:37 UTC, closed without merging